# Generated by Django 4.2.5 on 2023-10-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ImageField(default='profile.jpg', upload_to='profile/'),
            preserve_default=False,
        ),
    ]
